application: public-service2
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: /robots\.txt

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts
  
- url: /js
  static_dir: js

- url: .*
  script: main.py
